id = "mikrotik-rsc"
name = "MikroTik RouterOS Script"
description = "RSC language support for MikroTik RouterOS (7.22+) with syntax highlighting and command autocompletion."
version = "0.1.0"
schema_version = 1
authors = ["keiras94"]
repository = ""
languages = ["languages/rsc"]

[grammars.rsc]
repository = "/Users/Francisco/Developer/mikrotik-zed/grammar-bare.git"
rev = "af68d9588c1565f77c9fe9778bbd397d4727b79b"
