id = "mikrotik-rsc"
name = "MikroTik RouterOS Script"
description = "RSC language support for MikroTik RouterOS (7.22+) with syntax highlighting and command autocompletion."
version = "0.1.0"
schema_version = 1
authors = ["keiras94"]
repository = ""
languages = ["languages/rsc"]

[grammars.rsc]
repository = "/Users/Francisco/Developer/mikrotik-zed/grammar-bare.git"
rev = "53a7ab10419852ba2dc027af80a1bed50757ab31"

[language_servers.rsc-ls]
name = "RSC Language Server"
languages = ["MikroTik Script"]
